package com.user.entity;

import lombok.Data;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;

/**
 * Entity class representing an address.
 * This class maps to the "Address" table in the database and provides fields for address details.
 */
@Entity
@Data
public class Address {
  /**
   * The unique identifier for the address.
   * This field is auto-generated by the database.
   */
  @Id
  @GeneratedValue(strategy = GenerationType.IDENTITY)
  @Column(name = "address_id")
  private Integer id;
  /**
   * The street part of the address.
   * This field cannot be null.
   */
  @Column(name = "street", nullable = false)
  private String street;
  /**
   * The state where the address is located.
   * This field cannot be null.
   */
  @Column(name = "state", nullable = false)
  private String state;

  /**
   * The city where the address is located.
   * This field cannot be null.
   */
  @Column(name = "city", nullable = false)
  private String city;

  /**
   * The postal code (PIN code) for the address.
   * This field cannot be null.
   */
  @Column(name = "pincode", nullable = false)
  private Integer pinCode;

  /**
   * The ID of the user associated with this address.
   * This field is not part of the primary key and can be used to link the address to a specific user.
   */
  private Integer userId;

}

