package com.user.entity;

import com.user.util.Constant;
import com.user.util.Role;
import lombok.Data;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Entity class representing a user.
 * This class maps to the "users" table in the database and provides fields for user details.
 */
@Entity
@Table(name = "users")
@Data
public class User {

  /**
   * The unique identifier for the user.
   * This field is auto-generated by the database.
   */
  @Id
  @GeneratedValue(strategy = GenerationType.IDENTITY)
  @Column(name = "user_id")
  private Integer id;

  /**
   * The name of the user.
   * This field cannot be null.
   */
  @Column(name = "name", nullable = false)
  private String name;

  /**
   * The password for the user account.
   * This field cannot be null.
   */
  @Column(name = "password", nullable = false)
  private String password;


  /**
   * The email address of the user.
   * This field cannot be null.
   */
  @Column(name = "email", nullable = false)
  private String email;

  /**
   * The balance in the user's wallet.
   * This field is initialized to 1000.0 by default.
   */
  @Column(name = "walletBalance")
  private Double walletBalance = Constant.DEFAULT_WALLET_BALANCE;

  /**
   * The phone number of the user.
   * This field cannot be null.
   */
  @Column(name = "phoneNo", nullable = false)
  private String phoneNo;

  /**
   * The role assigned to the user.
   * This field cannot be null and is represented as a string in the database.
   */
  @Enumerated(EnumType.STRING)
  @Column(name = "role", nullable = false)
  private Role role;

}


