package com.restaurants.entities;

import lombok.Data;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;


/**
 * Represents a category of food items within a restaurant.
 * <p>
 * This entity class maps to the "category" table in the database.
 * It contains fields for the unique identifier, the restaurant ID,
 * and the name of the category.
 * </p>
 */
@Entity
@Data
public class Category {
  /**
   * The unique identifier for the category.
   * It is auto-generated by the database.
   */
  @Id
  @GeneratedValue(strategy = GenerationType.IDENTITY)
  private Integer id;

  /**
   * The ID of the restaurant to which this category belongs.
   * This field is not nullable.
   */
  @Column(name = "rest_id", nullable = false)
  private Integer restaurantId;

  /**
   * The name of the category.
   * This field is not nullable.
   */
  @Column(name = "name", nullable = false)
  private String name;
}
