package com.restaurants.entities;

import lombok.Data;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;


/**
 * Represents a food item offered by a restaurant.
 * <p>
 * This entity class maps to the "food_item" table in the database.
 * It contains fields for the unique identifier, the food name,
 * the restaurant ID, a description of the food item, the category ID,
 * availability status, price, and an optional image URL.
 * </p>
 */
@Entity
@Data
public class FoodItem {

  /**
   * The unique identifier for the food item.
   * It is auto-generated by the database.
   */
  @Id
  @GeneratedValue(strategy = GenerationType.IDENTITY)
  private Integer id;

  /**
   * The name of the food item.
   * This field is not nullable.
   */
  @Column(name = "food_name", nullable = false)
  private String foodName;

  /**
   * The ID of the restaurant that offers this food item.
   * This field is not nullable.
   */
  @Column(name = "restaurant_id", nullable = false)
  private Integer restaurantId;

  /**
   * A description of the food item.
   * This field is not nullable.
   */
  @Column(name = "description", nullable = false)
  private String description;

  /**
   * The ID of the category to which this food item belongs.
   * This field is not nullable.
   */
  @Column(name = "category_id", nullable = false)
  private Integer categoryId;

  /**
   * Indicates whether the food item is available for order.
   * This field is not nullable.
   */
  @Column(name = "is_available", nullable = false)
  private Boolean isAvailable;

  /**
   * The price of the food item.
   * This field is not nullable.
   */
  @Column(name = "price", nullable = false)
  private Double price;

  /**
   * The URL of the image representing the food item.
   * This field is optional and can be null.
   */
  @Column(name = "image_url")
  private String imageUrl;
}
