package com.restaurants.entities;

import lombok.Data;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Lob;


/**
 * Represents a restaurant entity.
 * <p>
 * This entity class maps to the "restaurant" table in the database.
 * It includes fields for the unique identifier, user ID, restaurant name,
 * address, contact number, description, and an optional image URL.
 * </p>
 */
@Data
@Entity
public class Restaurant {
  /**
   * The unique identifier for the restaurant.
   * It is auto-generated by the database.
   */
  @Id
  @GeneratedValue(strategy = GenerationType.IDENTITY)
  @Column(name = "restaurant_id")
  private Integer id;

  /**
   * The ID of the user associated with the restaurant.
   * This field is not nullable.
   */
  @Column(name = "user_id", nullable = false)
  private Integer userId;

  /**
   * The name of the restaurant.
   * This field is not nullable.
   */
  @Column(name = "rest_name", nullable = false)
  private String restaurantName;


  /**
   * The address of the restaurant.
   * This field is not nullable.
   */
  @Column(name = "address", nullable = false)
  private String address;

  /**
   * The contact number of the restaurant.
   * This field is not nullable.
   */
  @Column(name = "contact_number", nullable = false)
  private String contactNumber;

  /**
   * A description of the restaurant.
   * This field is not nullable.
   */
  @Column(name = "description", nullable = false)
  private String description;

  /**
   * The URL of an image representing the restaurant.
   * This field is optional and can be null.
   */
  @Lob
  @Column(name = "imageData")
  private byte[] imageData;
}
